/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Partner Service REST APIs
 * Partner Service REST APIs Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * EcomPartner Entity
 */
export interface EcomPartner {
  autoMake?: string;
  autoModel?: string;
  autoYear?: string;
  cartUrl: string;
  diameter?: string;
  ecomPartnerId: number;
  extraFields?: string;
  frontRear: string;
  partNumber: string;
  post?: string;
  price: string;
  quantity?: string;
  rearDiameter?: string;
  rearPartNumber?: string;
  rearPrice?: string;
  rearQuantity?: string;
  rearTireRatio?: string;
  rearTireWidth?: string;
  rearWidth?: string;
  smallImage?: string;
  tireRatio?: string;
  tireWidth?: string;
  wheelFinish?: string;
  wheelMake?: string;
  wheelModel?: string;
  width?: string;
}
