/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Partner Service REST APIs
 * Partner Service REST APIs Documentation
 * OpenAPI spec version: 1.0
 */

export * from './deletePartnerByIdParams';
export * from './ecomPartner';
export * from './getEcomPartnerByPartnerIdParams';
export * from './getPartnerByNameParams';
export * from './partner';