/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Partner Service REST APIs
 * Partner Service REST APIs Documentation
 * OpenAPI spec version: 1.0
 */
import type { EcomPartner } from './ecomPartner';

/**
 * Partner Entity
 */
export interface Partner {
  brandFilter?: string;
  companyName?: string;
  dateCreated?: string;
  dateLastUsed?: string;
  dollarMarkup: number;
  ecomPartner?: EcomPartner;
  excludePriceMessage?: string;
  footer?: string;
  header?: string;
  homeUrl?: string;
  partnerId?: number;
  partnerName: string;
  partnerType?: string;
  pdfBackground?: string;
  pdfHeaderCopy?: string;
  pdfLogo?: string;
  percentMarkup: number;
  permissionsGroup?: string;
  showPdf?: string;
  totalSearches?: number;
  totalUses?: number;
  tpmsDollarMarkup?: number;
  tpmsPercentMarkup?: number;
}
