/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Partner Service REST APIs
 * Partner Service REST APIs Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  DeletePartnerByIdParams,
  EcomPartner,
  GetEcomPartnerByPartnerIdParams,
  GetPartnerByNameParams,
  Partner
} from './types'
import { customInstance } from '../../custom-instance';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary Retrieve a Partner by name
 */
export const getPartnerByName = (
    params: GetPartnerByNameParams,
 ) => {
      
      
      return customInstance<Partner>(
      {url: `/api/partners`, method: 'get',
        params
    },
      );
    }
  

export const getGetPartnerByNameQueryKey = (params: GetPartnerByNameParams,) => {
    
    return [`/api/partners`, ...(params ? [params]: [])] as const;
    }

    
export const getGetPartnerByNameQueryOptions = <TData = Awaited<ReturnType<typeof getPartnerByName>>, TError = void>(params: GetPartnerByNameParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPartnerByName>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPartnerByNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPartnerByName>>> = () => getPartnerByName(params, );

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPartnerByName>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPartnerByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getPartnerByName>>>
export type GetPartnerByNameQueryError = void

/**
 * @summary Retrieve a Partner by name
 */
export const useGetPartnerByName = <TData = Awaited<ReturnType<typeof getPartnerByName>>, TError = void>(
 params: GetPartnerByNameParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPartnerByName>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPartnerByNameQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create a Partner
 */
export const createPartner = (
    partner: Partner,
 ) => {
      
      
      return customInstance<Partner>(
      {url: `/api/partners`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: partner
    },
      );
    }
  


export const getCreatePartnerMutationOptions = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPartner>>, TError,{data: Partner}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPartner>>, TError,{data: Partner}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPartner>>, {data: Partner}> = (props) => {
          const {data} = props ?? {};

          return  createPartner(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreatePartnerMutationResult = NonNullable<Awaited<ReturnType<typeof createPartner>>>
    export type CreatePartnerMutationBody = Partner
    export type CreatePartnerMutationError = unknown

    /**
 * @summary Create a Partner
 */
export const useCreatePartner = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPartner>>, TError,{data: Partner}, TContext>, }
) => {

      const mutationOptions = getCreatePartnerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete a Partner by Id
 */
export const deletePartnerById = (
    params: DeletePartnerByIdParams,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/partners`, method: 'delete',
        params
    },
      );
    }
  


export const getDeletePartnerByIdMutationOptions = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePartnerById>>, TError,{params: DeletePartnerByIdParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePartnerById>>, TError,{params: DeletePartnerByIdParams}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePartnerById>>, {params: DeletePartnerByIdParams}> = (props) => {
          const {params} = props ?? {};

          return  deletePartnerById(params,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type DeletePartnerByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deletePartnerById>>>
    
    export type DeletePartnerByIdMutationError = unknown

    /**
 * @summary Delete a Partner by Id
 */
export const useDeletePartnerById = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePartnerById>>, TError,{params: DeletePartnerByIdParams}, TContext>, }
) => {

      const mutationOptions = getDeletePartnerByIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Retrieve an Ecom Partner by Partner Id
 */
export const getEcomPartnerByPartnerId = (
    params: GetEcomPartnerByPartnerIdParams,
 ) => {
      
      
      return customInstance<EcomPartner>(
      {url: `/api/partners/ecom`, method: 'get',
        params
    },
      );
    }
  

export const getGetEcomPartnerByPartnerIdQueryKey = (params: GetEcomPartnerByPartnerIdParams,) => {
    
    return [`/api/partners/ecom`, ...(params ? [params]: [])] as const;
    }

    
export const getGetEcomPartnerByPartnerIdQueryOptions = <TData = Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>, TError = void>(params: GetEcomPartnerByPartnerIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEcomPartnerByPartnerIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>> = () => getEcomPartnerByPartnerId(params, );

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEcomPartnerByPartnerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>>
export type GetEcomPartnerByPartnerIdQueryError = void

/**
 * @summary Retrieve an Ecom Partner by Partner Id
 */
export const useGetEcomPartnerByPartnerId = <TData = Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>, TError = void>(
 params: GetEcomPartnerByPartnerIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEcomPartnerByPartnerId>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetEcomPartnerByPartnerIdQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create an Ecom Partner
 */
export const createEcomPartner = (
    ecomPartner: EcomPartner,
 ) => {
      
      
      return customInstance<EcomPartner>(
      {url: `/api/partners/ecom`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: ecomPartner
    },
      );
    }
  


export const getCreateEcomPartnerMutationOptions = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEcomPartner>>, TError,{data: EcomPartner}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createEcomPartner>>, TError,{data: EcomPartner}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEcomPartner>>, {data: EcomPartner}> = (props) => {
          const {data} = props ?? {};

          return  createEcomPartner(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type CreateEcomPartnerMutationResult = NonNullable<Awaited<ReturnType<typeof createEcomPartner>>>
    export type CreateEcomPartnerMutationBody = EcomPartner
    export type CreateEcomPartnerMutationError = unknown

    /**
 * @summary Create an Ecom Partner
 */
export const useCreateEcomPartner = <TError = unknown,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEcomPartner>>, TError,{data: EcomPartner}, TContext>, }
) => {

      const mutationOptions = getCreateEcomPartnerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Retrieve a Partner by Id
 */
export const getPartnerById = (
    partnerId: number,
 ) => {
      
      
      return customInstance<Partner>(
      {url: `/api/partners/${partnerId}`, method: 'get'
    },
      );
    }
  

export const getGetPartnerByIdQueryKey = (partnerId: number,) => {
    
    return [`/api/partners/${partnerId}`] as const;
    }

    
export const getGetPartnerByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPartnerById>>, TError = void>(partnerId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPartnerById>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPartnerByIdQueryKey(partnerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPartnerById>>> = () => getPartnerById(partnerId, );

      

      

   return  { queryKey, queryFn, enabled: !!(partnerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPartnerById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPartnerByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPartnerById>>>
export type GetPartnerByIdQueryError = void

/**
 * @summary Retrieve a Partner by Id
 */
export const useGetPartnerById = <TData = Awaited<ReturnType<typeof getPartnerById>>, TError = void>(
 partnerId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPartnerById>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetPartnerByIdQueryOptions(partnerId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



